### ISSUE TITLE
Safari

### ISSUE THREAD

**Issue by llKoull** [alchimya/cc-crazy-monkey#1]
Hi!

I've been doing some tests with your example, because we are working in a similar game. The problem is that when i open the game using Safari 10.0 on MacOS Sierra in a 2015 Macbook Pro Retina the whole system goes really slow.

I don't know why, but the FPS are really low and all the system's animation (like minimize a windows or open an App) are really slow.

I also tested to run the game in Chrome. The FPS are more stable at 30 and the system doesn't seems to slow down.

I'm having the same issue with my slot game and i think that it could be some kind of problem with the image rescaling and the retina displays or the management of the canvas in Safari.

Thanks!

**Comment by alchimya** [comment]
Hi,
my configuration is Macboock Pro retina 2013, MacOs Sierra.
Using CocosCreator 1.2.2 I made a build with a web desktop platform with a preview resolution of 1280x720
FPS for me is always 60 FPS and seems working fine.

Did you try to reduce the browser window to understand if actually is a rendering/scaling issue?
Let me know.
Cheers,
Domenico

**Comment by llKoull** [comment]
Hi alchimya!

I made a build with the same Cocos Creator version but i choosed web mobile platform. I tried to reduce the browser window and the performance increases. It's because i think that is some kind of problem with the scaling.

The performace goes down when i enter in full screen mode in safari. I can send you a video to show you the issue. 

Thanks!

**Comment by alchimya** [comment]
Hi,
Im not sure that a web mobile platform build is optimised to run within a desktop browser...makes sense?
What about a web mobile build running into a mobile web browser?
Anyway try to ask to the Cocos Creator team if there are differences on building for mobile and desktop web platforms.
Cheers,
Domenico

**Comment by llKoull** [comment]
Hi Alchimya!

I'm having the same issues with the desktop platform configuration. 

And yes, using mobile platform configuration I'm having framerate problems on my iPhone 7 or iPad Air.

I will try to ask to the cocos creators :) 

Thanks!

**Comment by alchimya** [comment]
Hi llKoull,
anyway try to understand if there is a bottleneck within my code. For exampleI I would like to suggest to take a look to the reel.js class.
Eventually I'll be happy to review and merge your pull request.
Many thanks,
Domenico

**Comment by llKoull** [comment]
I did not found any bottleneck, and i'm having the same issue in my code (that is different). I let you know if i find anything ;)

**Comment by llKoull** [comment]
I fond a different issue thank i think that it can be fixed modifying reel.js  Some times, when the first or the last element of the reel is the winner index, the previous or next item are not placed in the correct position. I attach a picture to show you the issue (Look at the last element of the last reel).

I know that the problem is in reel.js but i couldn't find where :S

![1](https://cloud.githubusercontent.com/assets/5525265/19408692/e3e71914-92c3-11e6-8684-23886a156ad5.jpeg)

**Comment by alchimya** [comment]
Hi llKoull,
many thanks for your deep testing/debugging.
I'll try to find and fix the bug of that lazy element...lol!
Cheers,
Dom

**Comment by alchimya** [comment]
Hi llKoull,
I fixed the last issue that you raised.
Please check it and if everything is ok then close this issue.
Please next time open separate tasks for different issues, so it will be much better to find and check them.  :)
Let me know,
Dom

**Comment by llKoull** [comment]
Yeah! It seems to be working now 😁

Thanks Alchimya!
